version: '2'
services:
  db:
    image: postgres
    container_name: sonar-pg
    restart: always
    environment:
      - POSTGRES_USER=sonar 
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgres/volumes:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - net_sonar
  sonarqube:
    image: sonarqube
    container_name: sonar-sonar
    restart: always
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar 
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - ./sonar-l10n-zh-plugin-1.16.jar:/opt/sonarqube/extensions/plugins/sonar-l10n-zh-plugin-1.16.jar
    ports:
      - 9000:9000
    networks:
      - net_sonar
      
networks:
  net_sonar:
    external: false

